readdirplus fails, duplicate children
result on go version go1.16.5 linux/amd64; linux 5.11.0-18-generic

11:49:13.872883 rx 193042: READDIRPLUS n1 {Fh 1 [202 +4096)  L 0 RDONLY,0x8000}
11:49:13.872890 tx 193042:     OK
11:49:13.872910 rx 193044: RELEASEDIR n1 {Fh 1 0x8000  L0}
11:49:13.872913 tx 193044:     OK
    inmemory_example_test.go:149: uniqueness fail, saw name "added_child_134" idx 39 at index 40 before
    inmemory_example_test.go:149: uniqueness fail, saw name "added_child_138" idx 44 at index 45 before
    inmemory_example_test.go:149: uniqueness fail, saw name "added_child_158" idx 66 at index 67 before
    inmemory_example_test.go:149: uniqueness fail, saw name "added_child_160" idx 70 at index 71 before
    inmemory_example_test.go:149: uniqueness fail, saw name "added_child_18" idx 91 at index 92 before
    inmemory_example_test.go:149: uniqueness fail, saw name "added_child_30" idx 123 at index 124 before
    inmemory_example_test.go:149: uniqueness fail, saw name "added_child_35" idx 129 at index 130 before
    inmemory_example_test.go:149: uniqueness fail, saw name "added_child_45" idx 141 at index 142 before
    inmemory_example_test.go:149: uniqueness fail, saw name "added_child_53" idx 150 at index 151 before
    inmemory_example_test.go:154: failed, got just 193 unique entries instead of 202 - failed at attempt #231
11:49:13.874609 received ENODEV (unmount request), thread exiting
11:49:13.874698 received ENODEV (unmount request), thread exiting
11:49:13.874700 received ENODEV (unmount request), thread exiting
11:49:13.874950 received ENODEV (unmount request), thread exiting
--- FAIL: TestManyFilesReadDir (7.05s)

FAIL